// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.

require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
<<<<<<< HEAD
require('../../js/affix.js')
=======
require('../../js/affix.js')
>>>>>>> cf15c47c8fedbe6c8061bd7d1bf1690a09daef0a
